export const capabilities = [
  { number: '01', slug: 'residential', title: 'Residential', scope: 'Homes · Villas · Renovations', image: '/media/rs-residence.png', lead: 'Homes designed around the life that will unfold inside them.', copy: 'We coordinate planning, civil work, services and finishing as one continuous build—protecting the design intent while keeping decisions, budgets and timelines visible.' },
  { number: '02', slug: 'commercial', title: 'Commercial', scope: 'Hospitality · Retail · Workspaces', image: '/media/coyaba-facade.webp', lead: 'Spaces that work as beautifully as they welcome.', copy: 'From destination hospitality to high-performing commercial environments, we balance guest experience, operational demands and long-term durability.' },
  { number: '03', slug: 'industrial', title: 'Industrial', scope: 'Facilities · Planning · Execution', image: '/media/rs-resort.png', lead: 'Infrastructure engineered around performance.', copy: 'We approach industrial projects through workflow, safety, service coordination and future capacity—delivering robust facilities ready for daily use.' },
  { number: '04', slug: 'interior-turnkey', title: 'Turnkey interiors', scope: 'Civil · Services · Materials · Finishes', image: '/media/soir7-interior-1.jpg', lead: 'One vision, resolved down to the final detail.', copy: 'Our turnkey team brings civil work, building services, procurement, custom execution and finishing under one accountable point of control.' },
];

export const caseStudies = [
  { slug: 'the-coyaba', number: '01', title: 'The Coyaba', type: 'Resort · Delivered', size: '98,000 square feet', location: 'Ludhiana', service: 'Construction · Planning · Interiors', lead: 'A hospitality destination shaped at the scale of an experience.', copy: 'RS Developers led construction, planning and interior execution across this 98,000-square-foot resort—coordinating the architecture, landscape-facing spaces and guest experience into one distinctive destination.', images: ['/media/coyaba-facade.webp', '/media/coyaba-garden.webp', '/media/coyaba-detail-1.webp', '/media/coyaba-detail-2.webp'], logo: '/brand/coyaba-logo.webp', brandUrl: 'https://coyaba.in/' },
  { slug: 'nirvana-luxury-hotel', number: '02', title: 'Nirvana Luxury Hotel', type: 'Hospitality · In progress', size: 'Expansion and renewal', location: 'Ludhiana', service: 'Expansion · Guest rooms · Banquet', lead: 'Renewing a landmark without losing what makes it recognisable.', copy: 'This evolving programme brings together a new expansion, considered guest-room renewal and banquet-hall services. Every intervention respects the operational demands and established character of a working luxury hotel.', images: ['/media/nirvana-facade.jpg', '/media/nirvana-pool.jpg', '/media/nirvana-interior.jpg'], logo: '/brand/nirvana-logo.png', brandUrl: 'https://www.nirvanahotels.co.in/' },
  { slug: 'gold-dust-residence', number: '03', title: 'Gold Dust Residence', type: 'Residential · Turnkey', size: '1,925 square feet', location: 'Ludhiana', service: 'Planning · Construction · Finishes', lead: 'A complete home, delivered through one clear line of responsibility.', copy: 'This 1,925-square-foot residence is being delivered as a true turnkey project—from requirements and planning through execution, coordination, finishing and handover.', images: ['/media/rs-residence.png'] },
  { slug: 'the-soir-7', number: '04', title: 'The Soir 7', type: 'Restaurant · Interiors', size: 'Hospitality interiors', location: 'Ludhiana', service: 'Interior execution · Hospitality', lead: 'An intimate restaurant shaped through atmosphere, material and light.', copy: 'The Soir 7 brings together warm materiality, layered lighting and carefully resolved details to create a memorable guest experience with a distinct sense of place.', images: ['/media/soir7-interior-1.jpg', '/media/soir7-interior-2.jpg', '/media/soir7-interior-3.jpg'], brandUrl: 'https://www.instagram.com/soir7xbabas/' },
];

export const processSteps = ['Understand the requirements', 'Site visit and consultation', 'Estimate and BOQ', 'Final discussion and agreement', 'Planning and execution', 'Snagging and final handover'];
